spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recreation_db?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:pass}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,/app/uploads/
      add-mappings: true

server:
  error:
    whitelabel:
      enabled: false



